export type City = {
  id: string;
  name: string;
  region: string;
  tz: string;
  lat: number;
  lng: number;
};

export const CITY_CATALOG: City[] = [
  { id: "tokyo", name: "Tokyo", region: "Japan", tz: "Asia/Tokyo", lat: 35.6762, lng: 139.6503 },
  {
    id: "london",
    name: "London",
    region: "United Kingdom",
    tz: "Europe/London",
    lat: 51.5072,
    lng: -0.1276,
  },
  {
    id: "new-york",
    name: "New York",
    region: "United States",
    tz: "America/New_York",
    lat: 40.7128,
    lng: -74.006,
  },
  {
    id: "los-angeles",
    name: "Los Angeles",
    region: "United States",
    tz: "America/Los_Angeles",
    lat: 34.0522,
    lng: -118.2437,
  },
  {
    id: "dubai",
    name: "Dubai",
    region: "United Arab Emirates",
    tz: "Asia/Dubai",
    lat: 25.2048,
    lng: 55.2708,
  },
  {
    id: "sydney",
    name: "Sydney",
    region: "Australia",
    tz: "Australia/Sydney",
    lat: -33.8688,
    lng: 151.2093,
  },
  {
    id: "reykjavik",
    name: "Reykjavík",
    region: "Iceland",
    tz: "Atlantic/Reykjavik",
    lat: 64.1466,
    lng: -21.9426,
  },
  {
    id: "sao-paulo",
    name: "São Paulo",
    region: "Brazil",
    tz: "America/Sao_Paulo",
    lat: -23.5505,
    lng: -46.6333,
  },
  { id: "paris", name: "Paris", region: "France", tz: "Europe/Paris", lat: 48.8566, lng: 2.3522 },
  { id: "berlin", name: "Berlin", region: "Germany", tz: "Europe/Berlin", lat: 52.52, lng: 13.405 },
  {
    id: "madrid",
    name: "Madrid",
    region: "Spain",
    tz: "Europe/Madrid",
    lat: 40.4168,
    lng: -3.7038,
  },
  {
    id: "lisbon",
    name: "Lisbon",
    region: "Portugal",
    tz: "Europe/Lisbon",
    lat: 38.7223,
    lng: -9.1393,
  },
  { id: "rome", name: "Rome", region: "Italy", tz: "Europe/Rome", lat: 41.9028, lng: 12.4964 },
  {
    id: "athens",
    name: "Athens",
    region: "Greece",
    tz: "Europe/Athens",
    lat: 37.9838,
    lng: 23.7275,
  },
  {
    id: "istanbul",
    name: "Istanbul",
    region: "Türkiye",
    tz: "Europe/Istanbul",
    lat: 41.0082,
    lng: 28.9784,
  },
  {
    id: "moscow",
    name: "Moscow",
    region: "Russia",
    tz: "Europe/Moscow",
    lat: 55.7558,
    lng: 37.6173,
  },
  {
    id: "stockholm",
    name: "Stockholm",
    region: "Sweden",
    tz: "Europe/Stockholm",
    lat: 59.3293,
    lng: 18.0686,
  },
  { id: "oslo", name: "Oslo", region: "Norway", tz: "Europe/Oslo", lat: 59.9139, lng: 10.7522 },
  {
    id: "helsinki",
    name: "Helsinki",
    region: "Finland",
    tz: "Europe/Helsinki",
    lat: 60.1699,
    lng: 24.9384,
  },
  {
    id: "dublin",
    name: "Dublin",
    region: "Ireland",
    tz: "Europe/Dublin",
    lat: 53.3498,
    lng: -6.2603,
  },
  {
    id: "amsterdam",
    name: "Amsterdam",
    region: "Netherlands",
    tz: "Europe/Amsterdam",
    lat: 52.3676,
    lng: 4.9041,
  },
  {
    id: "zurich",
    name: "Zürich",
    region: "Switzerland",
    tz: "Europe/Zurich",
    lat: 47.3769,
    lng: 8.5417,
  },
  { id: "cairo", name: "Cairo", region: "Egypt", tz: "Africa/Cairo", lat: 30.0444, lng: 31.2357 },
  { id: "lagos", name: "Lagos", region: "Nigeria", tz: "Africa/Lagos", lat: 6.5244, lng: 3.3792 },
  {
    id: "nairobi",
    name: "Nairobi",
    region: "Kenya",
    tz: "Africa/Nairobi",
    lat: -1.2921,
    lng: 36.8219,
  },
  {
    id: "cape-town",
    name: "Cape Town",
    region: "South Africa",
    tz: "Africa/Johannesburg",
    lat: -33.9249,
    lng: 18.4241,
  },
  {
    id: "marrakesh",
    name: "Marrakesh",
    region: "Morocco",
    tz: "Africa/Casablanca",
    lat: 31.6295,
    lng: -7.9811,
  },
  {
    id: "tel-aviv",
    name: "Tel Aviv",
    region: "Israel",
    tz: "Asia/Jerusalem",
    lat: 32.0853,
    lng: 34.7818,
  },
  { id: "doha", name: "Doha", region: "Qatar", tz: "Asia/Qatar", lat: 25.2854, lng: 51.531 },
  {
    id: "karachi",
    name: "Karachi",
    region: "Pakistan",
    tz: "Asia/Karachi",
    lat: 24.8607,
    lng: 67.0011,
  },
  { id: "mumbai", name: "Mumbai", region: "India", tz: "Asia/Kolkata", lat: 19.076, lng: 72.8777 },
  { id: "delhi", name: "Delhi", region: "India", tz: "Asia/Kolkata", lat: 28.6139, lng: 77.209 },
  {
    id: "bengaluru",
    name: "Bengaluru",
    region: "India",
    tz: "Asia/Kolkata",
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    id: "kathmandu",
    name: "Kathmandu",
    region: "Nepal",
    tz: "Asia/Kathmandu",
    lat: 27.7172,
    lng: 85.324,
  },
  {
    id: "bangkok",
    name: "Bangkok",
    region: "Thailand",
    tz: "Asia/Bangkok",
    lat: 13.7563,
    lng: 100.5018,
  },
  {
    id: "singapore",
    name: "Singapore",
    region: "Singapore",
    tz: "Asia/Singapore",
    lat: 1.3521,
    lng: 103.8198,
  },
  {
    id: "jakarta",
    name: "Jakarta",
    region: "Indonesia",
    tz: "Asia/Jakarta",
    lat: -6.2088,
    lng: 106.8456,
  },
  {
    id: "hong-kong",
    name: "Hong Kong",
    region: "Hong Kong SAR",
    tz: "Asia/Hong_Kong",
    lat: 22.3193,
    lng: 114.1694,
  },
  {
    id: "shanghai",
    name: "Shanghai",
    region: "China",
    tz: "Asia/Shanghai",
    lat: 31.2304,
    lng: 121.4737,
  },
  {
    id: "beijing",
    name: "Beijing",
    region: "China",
    tz: "Asia/Shanghai",
    lat: 39.9042,
    lng: 116.4074,
  },
  {
    id: "seoul",
    name: "Seoul",
    region: "South Korea",
    tz: "Asia/Seoul",
    lat: 37.5665,
    lng: 126.978,
  },
  { id: "taipei", name: "Taipei", region: "Taiwan", tz: "Asia/Taipei", lat: 25.033, lng: 121.5654 },
  {
    id: "manila",
    name: "Manila",
    region: "Philippines",
    tz: "Asia/Manila",
    lat: 14.5995,
    lng: 120.9842,
  },
  {
    id: "perth",
    name: "Perth",
    region: "Australia",
    tz: "Australia/Perth",
    lat: -31.9523,
    lng: 115.8613,
  },
  {
    id: "melbourne",
    name: "Melbourne",
    region: "Australia",
    tz: "Australia/Melbourne",
    lat: -37.8136,
    lng: 144.9631,
  },
  {
    id: "auckland",
    name: "Auckland",
    region: "New Zealand",
    tz: "Pacific/Auckland",
    lat: -36.8485,
    lng: 174.7633,
  },
  {
    id: "honolulu",
    name: "Honolulu",
    region: "United States",
    tz: "Pacific/Honolulu",
    lat: 21.3069,
    lng: -157.8583,
  },
  {
    id: "anchorage",
    name: "Anchorage",
    region: "United States",
    tz: "America/Anchorage",
    lat: 61.2181,
    lng: -149.9003,
  },
  {
    id: "vancouver",
    name: "Vancouver",
    region: "Canada",
    tz: "America/Vancouver",
    lat: 49.2827,
    lng: -123.1207,
  },
  {
    id: "denver",
    name: "Denver",
    region: "United States",
    tz: "America/Denver",
    lat: 39.7392,
    lng: -104.9903,
  },
  {
    id: "chicago",
    name: "Chicago",
    region: "United States",
    tz: "America/Chicago",
    lat: 41.8781,
    lng: -87.6298,
  },
  {
    id: "toronto",
    name: "Toronto",
    region: "Canada",
    tz: "America/Toronto",
    lat: 43.6532,
    lng: -79.3832,
  },
  {
    id: "mexico-city",
    name: "Mexico City",
    region: "Mexico",
    tz: "America/Mexico_City",
    lat: 19.4326,
    lng: -99.1332,
  },
  {
    id: "bogota",
    name: "Bogotá",
    region: "Colombia",
    tz: "America/Bogota",
    lat: 4.711,
    lng: -74.0721,
  },
  { id: "lima", name: "Lima", region: "Peru", tz: "America/Lima", lat: -12.0464, lng: -77.0428 },
  {
    id: "santiago",
    name: "Santiago",
    region: "Chile",
    tz: "America/Santiago",
    lat: -33.4489,
    lng: -70.6693,
  },
  {
    id: "buenos-aires",
    name: "Buenos Aires",
    region: "Argentina",
    tz: "America/Argentina/Buenos_Aires",
    lat: -34.6037,
    lng: -58.3816,
  },
  {
    id: "rio",
    name: "Rio de Janeiro",
    region: "Brazil",
    tz: "America/Sao_Paulo",
    lat: -22.9068,
    lng: -43.1729,
  },
  { id: "tromso", name: "Tromsø", region: "Norway", tz: "Europe/Oslo", lat: 69.6492, lng: 18.9553 },
  {
    id: "ushuaia",
    name: "Ushuaia",
    region: "Argentina",
    tz: "America/Argentina/Ushuaia",
    lat: -54.8019,
    lng: -68.303,
  },
];

export const DEFAULT_CITY_IDS = [
  "tokyo",
  "london",
  "new-york",
  "los-angeles",
  "dubai",
  "sydney",
  "reykjavik",
  "sao-paulo",
];

export function findCity(id: string): City | undefined {
  return CITY_CATALOG.find((c) => c.id === id);
}
